#!/usr/bin/env python3
"""
bleumr-gen — Code Bleu Project Generator

Scaffolds full project structures for common frameworks.
Usage:
  python bleumr-gen.py <template> <project-name> [--path /custom/path]

Templates:
  fastapi     — FastAPI REST API with uvicorn, CORS, health check, .env
  flask       — Flask app with blueprints, templates, static
  django      — Django project with app, models, views, urls
  cli         — Python CLI tool with argparse, rich output
  package     — Python package with pyproject.toml, tests, src layout
  react       — React + Vite + TypeScript + Tailwind
  next        — Next.js 14 App Router + TypeScript + Tailwind
  electron    — Electron + React + Vite + TypeScript

Examples:
  python bleumr-gen.py fastapi my-api
  python bleumr-gen.py flask my-app --path ~/projects
  python bleumr-gen.py cli my-tool
"""

import os
import sys
import argparse
import textwrap
from pathlib import Path
from datetime import datetime

# ── Templates ────────────────────────────────────────────────────────────────

TEMPLATES = {}

# ── FastAPI ──────────────────────────────────────────────────────────────────

TEMPLATES['fastapi'] = {
    'requirements.txt': textwrap.dedent("""\
        fastapi>=0.110.0
        uvicorn[standard]>=0.27.0
        python-dotenv>=1.0.0
        pydantic>=2.5.0
        httpx>=0.26.0
    """),
    '.env': textwrap.dedent("""\
        APP_NAME={name}
        APP_ENV=development
        DEBUG=true
        HOST=0.0.0.0
        PORT=8000
        CORS_ORIGINS=http://localhost:3000,http://localhost:5173
    """),
    '.gitignore': textwrap.dedent("""\
        __pycache__/
        *.pyc
        .env
        .venv/
        venv/
        dist/
        *.egg-info/
        .pytest_cache/
    """),
    'app/__init__.py': '',
    'app/main.py': textwrap.dedent("""\
        from fastapi import FastAPI
        from fastapi.middleware.cors import CORSMiddleware
        from dotenv import load_dotenv
        import os

        load_dotenv()

        app = FastAPI(
            title=os.getenv("APP_NAME", "{name}"),
            version="0.1.0",
            docs_url="/docs",
        )

        # CORS
        origins = os.getenv("CORS_ORIGINS", "").split(",")
        app.add_middleware(
            CORSMiddleware,
            allow_origins=origins,
            allow_credentials=True,
            allow_methods=["*"],
            allow_headers=["*"],
        )


        @app.get("/")
        async def root():
            return {{"message": "Welcome to {name}", "status": "running"}}


        @app.get("/health")
        async def health():
            return {{"status": "ok"}}


        # Import routers
        from app.routes import api
        app.include_router(api.router, prefix="/api/v1")
    """),
    'app/routes/__init__.py': '',
    'app/routes/api.py': textwrap.dedent("""\
        from fastapi import APIRouter, HTTPException
        from pydantic import BaseModel
        from typing import Optional

        router = APIRouter()


        class Item(BaseModel):
            name: str
            description: Optional[str] = None
            price: float


        @router.get("/items")
        async def list_items():
            return {{"items": [], "count": 0}}


        @router.post("/items")
        async def create_item(item: Item):
            return {{"item": item.model_dump(), "id": 1}}


        @router.get("/items/{{item_id}}")
        async def get_item(item_id: int):
            raise HTTPException(status_code=404, detail="Item not found")
    """),
    'app/models/__init__.py': '',
    'app/services/__init__.py': '',
    'tests/__init__.py': '',
    'tests/test_main.py': textwrap.dedent("""\
        import pytest
        from httpx import AsyncClient, ASGITransport
        from app.main import app


        @pytest.fixture
        async def client():
            transport = ASGITransport(app=app)
            async with AsyncClient(transport=transport, base_url="http://test") as ac:
                yield ac


        @pytest.mark.anyio
        async def test_root(client):
            response = await client.get("/")
            assert response.status_code == 200
            assert "status" in response.json()


        @pytest.mark.anyio
        async def test_health(client):
            response = await client.get("/health")
            assert response.status_code == 200
            assert response.json()["status"] == "ok"
    """),
    'README.md': textwrap.dedent("""\
        # {name}

        FastAPI application generated by Code Bleu.

        ## Setup
        ```bash
        python -m venv venv
        source venv/bin/activate  # Windows: venv\\Scripts\\activate
        pip install -r requirements.txt
        ```

        ## Run
        ```bash
        uvicorn app.main:app --reload
        ```

        ## Test
        ```bash
        pip install pytest anyio httpx
        pytest
        ```
    """),
}

# ── Flask ────────────────────────────────────────────────────────────────────

TEMPLATES['flask'] = {
    'requirements.txt': textwrap.dedent("""\
        flask>=3.0.0
        python-dotenv>=1.0.0
        gunicorn>=21.2.0
    """),
    '.env': 'FLASK_APP=app\nFLASK_ENV=development\nSECRET_KEY=change-me-in-production\n',
    '.gitignore': '__pycache__/\n*.pyc\n.env\n.venv/\nvenv/\ninstance/\n',
    'app/__init__.py': textwrap.dedent("""\
        from flask import Flask
        from dotenv import load_dotenv
        import os

        load_dotenv()


        def create_app():
            app = Flask(__name__)
            app.config["SECRET_KEY"] = os.getenv("SECRET_KEY", "dev")

            from app.routes import main
            app.register_blueprint(main.bp)

            return app
    """),
    'app/routes/__init__.py': '',
    'app/routes/main.py': textwrap.dedent("""\
        from flask import Blueprint, jsonify, render_template

        bp = Blueprint("main", __name__)


        @bp.route("/")
        def index():
            return render_template("index.html")


        @bp.route("/api/health")
        def health():
            return jsonify(status="ok")
    """),
    'app/templates/index.html': textwrap.dedent("""\
        <!DOCTYPE html>
        <html lang="en">
        <head><meta charset="UTF-8"><title>{name}</title></head>
        <body>
            <h1>Welcome to {name}</h1>
            <p>Flask app generated by Code Bleu.</p>
        </body>
        </html>
    """),
    'app/static/.gitkeep': '',
    'run.py': textwrap.dedent("""\
        from app import create_app

        app = create_app()

        if __name__ == "__main__":
            app.run(debug=True)
    """),
    'README.md': textwrap.dedent("""\
        # {name}

        Flask application generated by Code Bleu.

        ## Setup
        ```bash
        python -m venv venv && source venv/bin/activate
        pip install -r requirements.txt
        ```

        ## Run
        ```bash
        python run.py
        ```
    """),
}

# ── CLI Tool ─────────────────────────────────────────────────────────────────

TEMPLATES['cli'] = {
    'pyproject.toml': textwrap.dedent("""\
        [build-system]
        requires = ["setuptools>=68.0", "wheel"]
        build-backend = "setuptools.backends._legacy:_Backend"

        [project]
        name = "{name}"
        version = "0.1.0"
        description = "CLI tool generated by Code Bleu"
        requires-python = ">=3.9"
        dependencies = ["rich>=13.0.0", "click>=8.1.0"]

        [project.scripts]
        {name} = "{name_under}.cli:main"
    """),
    '{name_under}/__init__.py': '__version__ = "0.1.0"\n',
    '{name_under}/cli.py': textwrap.dedent("""\
        import click
        from rich.console import Console
        from rich.table import Table

        console = Console()


        @click.group()
        @click.version_option()
        def main():
            \"\"\"{name} — CLI tool generated by Code Bleu.\"\"\"
            pass


        @main.command()
        @click.argument("name", default="world")
        def hello(name):
            \"\"\"Say hello.\"\"\"
            console.print(f"[bold green]Hello, {{name}}![/]")


        @main.command()
        def info():
            \"\"\"Show system info.\"\"\"
            table = Table(title="{name} Info")
            table.add_column("Key", style="cyan")
            table.add_column("Value", style="white")
            table.add_row("Version", "0.1.0")
            table.add_row("Python", "3.9+")
            console.print(table)


        if __name__ == "__main__":
            main()
    """),
    'tests/test_cli.py': textwrap.dedent("""\
        from click.testing import CliRunner
        from {name_under}.cli import main


        def test_hello():
            runner = CliRunner()
            result = runner.invoke(main, ["hello"])
            assert result.exit_code == 0


        def test_info():
            runner = CliRunner()
            result = runner.invoke(main, ["info"])
            assert result.exit_code == 0
    """),
    '.gitignore': '__pycache__/\n*.pyc\n.venv/\nvenv/\ndist/\n*.egg-info/\n',
    'README.md': textwrap.dedent("""\
        # {name}

        CLI tool generated by Code Bleu.

        ## Install
        ```bash
        pip install -e .
        ```

        ## Usage
        ```bash
        {name} hello
        {name} info
        ```
    """),
}

# ── Python Package ───────────────────────────────────────────────────────────

TEMPLATES['package'] = {
    'pyproject.toml': textwrap.dedent("""\
        [build-system]
        requires = ["setuptools>=68.0", "wheel"]
        build-backend = "setuptools.backends._legacy:_Backend"

        [project]
        name = "{name}"
        version = "0.1.0"
        description = "Python package generated by Code Bleu"
        requires-python = ">=3.9"
        license = {{text = "MIT"}}

        [project.optional-dependencies]
        dev = ["pytest>=7.0", "ruff>=0.1.0"]
    """),
    'src/{name_under}/__init__.py': textwrap.dedent("""\
        \"\"\"
        {name} — Python package generated by Code Bleu.
        \"\"\"

        __version__ = "0.1.0"
    """),
    'src/{name_under}/core.py': textwrap.dedent("""\
        \"\"\"Core module.\"\"\"


        def hello(name: str = "world") -> str:
            \"\"\"Return a greeting.\"\"\"
            return f"Hello, {{name}}!"
    """),
    'tests/__init__.py': '',
    'tests/test_core.py': textwrap.dedent("""\
        from {name_under}.core import hello


        def test_hello_default():
            assert hello() == "Hello, world!"


        def test_hello_name():
            assert hello("Code Bleu") == "Hello, Code Bleu!"
    """),
    '.gitignore': '__pycache__/\n*.pyc\n.venv/\nvenv/\ndist/\n*.egg-info/\n.pytest_cache/\n',
    'README.md': '# {name}\n\nPython package generated by Code Bleu.\n',
}

# ── React + Vite ─────────────────────────────────────────────────────────────

TEMPLATES['react'] = {
    'package.json': textwrap.dedent("""\
        {{
          "name": "{name}",
          "private": true,
          "version": "0.1.0",
          "type": "module",
          "scripts": {{
            "dev": "vite",
            "build": "tsc && vite build",
            "preview": "vite preview"
          }},
          "dependencies": {{
            "react": "^19.0.0",
            "react-dom": "^19.0.0"
          }},
          "devDependencies": {{
            "@types/react": "^19.0.0",
            "@types/react-dom": "^19.0.0",
            "@vitejs/plugin-react": "^4.3.0",
            "typescript": "^5.6.0",
            "vite": "^6.0.0",
            "tailwindcss": "^4.0.0",
            "@tailwindcss/vite": "^4.0.0"
          }}
        }}
    """),
    'vite.config.ts': textwrap.dedent("""\
        import {{ defineConfig }} from 'vite'
        import react from '@vitejs/plugin-react'
        import tailwindcss from '@tailwindcss/vite'

        export default defineConfig({{
          plugins: [react(), tailwindcss()],
        }})
    """),
    'tsconfig.json': textwrap.dedent("""\
        {{
          "compilerOptions": {{
            "target": "ES2020",
            "module": "ESNext",
            "lib": ["ES2020", "DOM", "DOM.Iterable"],
            "moduleResolution": "bundler",
            "jsx": "react-jsx",
            "strict": true,
            "skipLibCheck": true,
            "outDir": "dist"
          }},
          "include": ["src"]
        }}
    """),
    'index.html': textwrap.dedent("""\
        <!DOCTYPE html>
        <html lang="en">
        <head>
          <meta charset="UTF-8" />
          <meta name="viewport" content="width=device-width, initial-scale=1.0" />
          <title>{name}</title>
        </head>
        <body>
          <div id="root"></div>
          <script type="module" src="/src/main.tsx"></script>
        </body>
        </html>
    """),
    'src/main.tsx': textwrap.dedent("""\
        import React from 'react'
        import ReactDOM from 'react-dom/client'
        import App from './App'
        import './index.css'

        ReactDOM.createRoot(document.getElementById('root')!).render(
          <React.StrictMode>
            <App />
          </React.StrictMode>,
        )
    """),
    'src/App.tsx': textwrap.dedent("""\
        export default function App() {{
          return (
            <div className="min-h-screen bg-gray-950 text-white flex items-center justify-center">
              <div className="text-center">
                <h1 className="text-4xl font-bold mb-4">{name}</h1>
                <p className="text-gray-400">Built with Code Bleu</p>
              </div>
            </div>
          )
        }}
    """),
    'src/index.css': '@import "tailwindcss";\n',
    '.gitignore': 'node_modules/\ndist/\n.env\n',
}

# ── Django ───────────────────────────────────────────────────────────────────

TEMPLATES['django'] = {
    'requirements.txt': 'django>=5.0\npython-dotenv>=1.0.0\n',
    '.env': f'SECRET_KEY=change-me-{datetime.now().strftime("%Y%m%d")}\nDEBUG=True\n',
    '.gitignore': '__pycache__/\n*.pyc\n.env\n.venv/\nvenv/\ndb.sqlite3\nmedia/\nstaticfiles/\n',
    'manage.py': textwrap.dedent("""\
        #!/usr/bin/env python
        import os
        import sys

        def main():
            os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")
            from django.core.management import execute_from_command_line
            execute_from_command_line(sys.argv)

        if __name__ == "__main__":
            main()
    """),
    'config/__init__.py': '',
    'config/settings.py': textwrap.dedent("""\
        from pathlib import Path
        from dotenv import load_dotenv
        import os

        load_dotenv()
        BASE_DIR = Path(__file__).resolve().parent.parent
        SECRET_KEY = os.getenv("SECRET_KEY", "insecure-dev-key")
        DEBUG = os.getenv("DEBUG", "True") == "True"
        ALLOWED_HOSTS = ["*"]
        INSTALLED_APPS = [
            "django.contrib.admin", "django.contrib.auth",
            "django.contrib.contenttypes", "django.contrib.sessions",
            "django.contrib.messages", "django.contrib.staticfiles",
            "core",
        ]
        MIDDLEWARE = [
            "django.middleware.security.SecurityMiddleware",
            "django.contrib.sessions.middleware.SessionMiddleware",
            "django.middleware.common.CommonMiddleware",
            "django.middleware.csrf.CsrfViewMiddleware",
            "django.contrib.auth.middleware.AuthenticationMiddleware",
            "django.contrib.messages.middleware.MessageMiddleware",
        ]
        ROOT_URLCONF = "config.urls"
        TEMPLATES = [{{
            "BACKEND": "django.template.backends.django.DjangoTemplates",
            "DIRS": [BASE_DIR / "templates"],
            "APP_DIRS": True,
            "OPTIONS": {{"context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ]}},
        }}]
        DATABASES = {{"default": {{"ENGINE": "django.db.backends.sqlite3", "NAME": BASE_DIR / "db.sqlite3"}}}}
        STATIC_URL = "static/"
    """),
    'config/urls.py': textwrap.dedent("""\
        from django.contrib import admin
        from django.urls import path, include

        urlpatterns = [
            path("admin/", admin.site.urls),
            path("", include("core.urls")),
        ]
    """),
    'core/__init__.py': '',
    'core/models.py': '# Models go here\n',
    'core/views.py': textwrap.dedent("""\
        from django.http import JsonResponse

        def index(request):
            return JsonResponse({{"message": "Welcome to {name}", "status": "running"}})

        def health(request):
            return JsonResponse({{"status": "ok"}})
    """),
    'core/urls.py': textwrap.dedent("""\
        from django.urls import path
        from . import views

        urlpatterns = [
            path("", views.index),
            path("health/", views.health),
        ]
    """),
    'templates/.gitkeep': '',
    'README.md': textwrap.dedent("""\
        # {name}

        Django project generated by Code Bleu.

        ## Setup
        ```bash
        python -m venv venv && source venv/bin/activate
        pip install -r requirements.txt
        python manage.py migrate
        ```

        ## Run
        ```bash
        python manage.py runserver
        ```
    """),
}

# ── Next.js ──────────────────────────────────────────────────────────────────

TEMPLATES['next'] = {
    'package.json': textwrap.dedent("""\
        {{
          "name": "{name}",
          "version": "0.1.0",
          "private": true,
          "scripts": {{
            "dev": "next dev --turbopack",
            "build": "next build",
            "start": "next start"
          }},
          "dependencies": {{
            "next": "^15.0.0",
            "react": "^19.0.0",
            "react-dom": "^19.0.0"
          }},
          "devDependencies": {{
            "typescript": "^5.6.0",
            "@types/react": "^19.0.0",
            "@types/node": "^22.0.0",
            "tailwindcss": "^4.0.0",
            "@tailwindcss/postcss": "^4.0.0"
          }}
        }}
    """),
    'tsconfig.json': '{"compilerOptions":{"target":"ES2017","lib":["dom","dom.iterable","esnext"],"jsx":"preserve","module":"esnext","moduleResolution":"bundler","strict":true,"skipLibCheck":true,"paths":{"@/*":["./src/*"]}},"include":["next-env.d.ts","**/*.ts","**/*.tsx"]}\n',
    'next.config.ts': 'import type { NextConfig } from "next";\nconst config: NextConfig = {};\nexport default config;\n',
    'src/app/layout.tsx': textwrap.dedent("""\
        import "./globals.css";
        export const metadata = {{ title: "{name}", description: "Built with Code Bleu" }};
        export default function RootLayout({{ children }}: {{ children: React.ReactNode }}) {{
          return <html lang="en"><body>{{children}}</body></html>;
        }}
    """),
    'src/app/page.tsx': textwrap.dedent("""\
        export default function Home() {{
          return (
            <main className="min-h-screen bg-gray-950 text-white flex items-center justify-center">
              <div className="text-center">
                <h1 className="text-5xl font-bold mb-4">{name}</h1>
                <p className="text-gray-400">Built with Code Bleu</p>
              </div>
            </main>
          );
        }}
    """),
    'src/app/globals.css': '@import "tailwindcss";\n',
    '.gitignore': 'node_modules/\n.next/\nout/\n.env\n',
}

# ── Electron ─────────────────────────────────────────────────────────────────

TEMPLATES['electron'] = {
    'package.json': textwrap.dedent("""\
        {{
          "name": "{name}",
          "version": "0.1.0",
          "main": "electron/main.js",
          "scripts": {{
            "dev": "vite",
            "build": "vite build",
            "electron:dev": "concurrently \\"vite\\" \\"electron .\\"",
            "electron:build": "vite build && electron-builder"
          }},
          "dependencies": {{
            "react": "^19.0.0",
            "react-dom": "^19.0.0"
          }},
          "devDependencies": {{
            "@types/react": "^19.0.0",
            "@vitejs/plugin-react": "^4.3.0",
            "typescript": "^5.6.0",
            "vite": "^6.0.0",
            "electron": "^34.0.0",
            "concurrently": "^9.0.0"
          }}
        }}
    """),
    'electron/main.js': textwrap.dedent("""\
        const {{ app, BrowserWindow }} = require("electron");
        const path = require("path");

        function createWindow() {{
          const win = new BrowserWindow({{
            width: 1200,
            height: 800,
            webPreferences: {{ preload: path.join(__dirname, "preload.js"), contextIsolation: true }},
          }});
          if (process.env.VITE_DEV_SERVER_URL) win.loadURL(process.env.VITE_DEV_SERVER_URL);
          else win.loadFile(path.join(__dirname, "../dist/index.html"));
        }}

        app.whenReady().then(createWindow);
        app.on("window-all-closed", () => {{ if (process.platform !== "darwin") app.quit(); }});
    """),
    'electron/preload.js': 'const { contextBridge } = require("electron");\ncontextBridge.exposeInMainWorld("app", { platform: process.platform });\n',
    'src/main.tsx': 'import React from "react";\nimport ReactDOM from "react-dom/client";\nimport App from "./App";\nReactDOM.createRoot(document.getElementById("root")!).render(<App />);\n',
    'src/App.tsx': textwrap.dedent("""\
        export default function App() {{
          return <div style={{{{ minHeight: "100vh", background: "#0a0a0a", color: "white", display: "flex", alignItems: "center", justifyContent: "center" }}}}>
            <h1>{name}</h1>
          </div>;
        }}
    """),
    'index.html': '<!DOCTYPE html>\n<html><head><meta charset="UTF-8"><title>{name}</title></head>\n<body><div id="root"></div><script type="module" src="/src/main.tsx"></script></body></html>\n',
    '.gitignore': 'node_modules/\ndist/\n.env\n',
}


# ── Generator Engine ─────────────────────────────────────────────────────────

def generate(template_name: str, project_name: str, base_path: str = '.'):
    if template_name not in TEMPLATES:
        print(f"\n  Error: Unknown template '{template_name}'")
        print(f"  Available: {', '.join(TEMPLATES.keys())}\n")
        sys.exit(1)

    template = TEMPLATES[template_name]
    name_under = project_name.replace('-', '_').replace(' ', '_').lower()
    project_dir = Path(base_path) / project_name

    if project_dir.exists():
        print(f"\n  Error: Directory '{project_dir}' already exists.\n")
        sys.exit(1)

    print(f"\n  Creating {template_name} project: {project_name}")
    print(f"  Path: {project_dir.resolve()}\n")

    file_count = 0
    for file_path, content in template.items():
        # Replace placeholders in paths and content
        resolved_path = file_path.replace('{name_under}', name_under)
        resolved_content = content.replace('{name}', project_name).replace('{name_under}', name_under)

        full_path = project_dir / resolved_path
        full_path.parent.mkdir(parents=True, exist_ok=True)
        full_path.write_text(resolved_content)
        file_count += 1
        print(f"    + {resolved_path}")

    print(f"\n  Done! {file_count} files created.")
    print(f"\n  Next steps:")

    if template_name in ('fastapi', 'flask', 'django', 'cli', 'package'):
        print(f"    cd {project_name}")
        print(f"    python -m venv venv")
        print(f"    source venv/bin/activate")
        print(f"    pip install -r requirements.txt" if template_name != 'cli' else f"    pip install -e .")
        if template_name == 'fastapi':
            print(f"    uvicorn app.main:app --reload")
        elif template_name == 'flask':
            print(f"    python run.py")
        elif template_name == 'django':
            print(f"    python manage.py migrate && python manage.py runserver")
        elif template_name == 'cli':
            print(f"    {project_name} hello")
    else:
        print(f"    cd {project_name}")
        print(f"    npm install")
        print(f"    npm run dev")

    print()


# ── CLI ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description='Code Bleu Project Generator — scaffold full project structures',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent("""\
            templates:
              fastapi     FastAPI REST API with uvicorn, CORS, routes
              flask       Flask app with blueprints, templates
              django      Django project with app, views, urls
              cli         Python CLI with click + rich
              package     Python package with pyproject.toml + tests
              react       React + Vite + TypeScript + Tailwind
              next        Next.js 14 App Router + TypeScript
              electron    Electron + React + Vite
        """),
    )
    parser.add_argument('template', choices=list(TEMPLATES.keys()), help='Project template')
    parser.add_argument('name', help='Project name')
    parser.add_argument('--path', default='.', help='Base directory (default: current)')

    if len(sys.argv) < 3:
        parser.print_help()
        sys.exit(0)

    args = parser.parse_args()
    generate(args.template, args.name, args.path)


if __name__ == '__main__':
    main()
